<?php

use App\Video;
use Illuminate\Database\Migrations\Migration;

class ImportVideos extends Migration {
	public function up() {
		$tags = App\Tag::all();
		$tag = function ($name) use ($tags) {return $tags->where('name', $name)->first()->id;};
		$video = App\Video::create(json_decode('{"graphic": false, "service": "y", "title": "You Will Never Look at Your Life in the Same Way Again | Eye-Opening Speech!", "widescreen": true, "service_video_id": "Z3u7hXpOm58", "length": 1942, "mature": false}', true));
		$video->tags()->attach($tag("Ethics"));
		$video->tags()->attach($tag("Inspiring"));
		$video->tags()->attach($tag("Information"));
		$video->tags()->attach($tag("Speech"));
		$video->save();
		$video = App\Video::create(json_decode('{"graphic": false, "service": "y", "title": "Gary Yourofsky - The Most Important Speech You Will Ever Hear", "widescreen": true, "service_video_id": "U5hGQDLprA8", "length": 4164, "mature": false}', true));
		$video->tags()->attach($tag("Ethics"));
		$video->tags()->attach($tag("Inspiring"));
		$video->tags()->attach($tag("Information"));
		$video->tags()->attach($tag("Speech"));
		$video->save();
		$video = App\Video::create(json_decode('{"graphic": true, "service": "y", "title": "DAIRY IS SCARY! The industry explained in 5 minutes", "widescreen": true, "service_video_id": "UcN7SGGoCNI", "length": 340, "mature": false}', true));
		$video->tags()->attach($tag("Environment"));
		$video->tags()->attach($tag("Ethics"));
		$video->tags()->attach($tag("Health"));
		$video->tags()->attach($tag("Information"));
		$video->save();
		$video = App\Video::create(json_decode('{"graphic": false, "service": "y", "title": "Why Vegan? [NOT-GRAPHIC]", "widescreen": true, "service_video_id": "y2k4NHjAP84", "length": 288, "mature": false}', true));
		$video->tags()->attach($tag("Environment"));
		$video->tags()->attach($tag("Ethics"));
		$video->tags()->attach($tag("Information"));
		$video->save();
		$video = App\Video::create(json_decode('{"graphic": false, "service": "y", "title": "BEGINNER\'S GUIDE TO VEGANISM \u00bb how to go vegan", "widescreen": true, "service_video_id": "OJxMsypwnqg", "length": 721, "mature": false}', true));
		$video->tags()->attach($tag("Health"));
		$video->tags()->attach($tag("Information"));
		$video->tags()->attach($tag("Recipes"));
		$video->save();
		$video = App\Video::create(json_decode('{"graphic": false, "service": "y", "title": "How to Prevent Deficiencies on a Vegan Diet", "widescreen": true, "service_video_id": "zKwnMCEp3HM", "length": 844, "mature": false}', true));
		$video->tags()->attach($tag("Health"));
		$video->tags()->attach($tag("Information"));
		$video->tags()->attach($tag("Recipes"));
		$video->tags()->attach($tag("Science"));
		$video->save();
		$video = App\Video::create(json_decode('{"graphic": false, "service": "y", "title": "The Science of Vegan Fat Loss", "widescreen": true, "service_video_id": "bcN2HjOutEk", "length": 650, "mature": false}', true));
		$video->tags()->attach($tag("Health"));
		$video->tags()->attach($tag("Information"));
		$video->tags()->attach($tag("Science"));
		$video->save();
		$video = App\Video::create(json_decode('{"graphic": false, "service": "y", "title": "How to Become a Vegan Activist", "widescreen": true, "service_video_id": "oW682wH7078", "length": 630, "mature": false}', true));
		$video->tags()->attach($tag("Ethics"));
		$video->tags()->attach($tag("Inspiring"));
		$video->tags()->attach($tag("Activism"));
		$video->tags()->attach($tag("Philosophy"));
		$video->save();
		$video = App\Video::create(json_decode('{"graphic": true, "service": "y", "title": "Why Vegans Want You To Be Vegan", "widescreen": true, "service_video_id": "CTqFv_XMxHw", "length": 341, "mature": false}', true));
		$video->tags()->attach($tag("Inspiring"));
		$video->tags()->attach($tag("Philosophy"));
		$video->save();
		$video = App\Video::create(json_decode('{"graphic": false, "service": "y", "title": "How to Talk to Non-Vegans", "widescreen": true, "service_video_id": "PxCF_8sY54o", "length": 539, "mature": false}', true));
		$video->tags()->attach($tag("Ethics"));
		$video->tags()->attach($tag("Information"));
		$video->tags()->attach($tag("Activism"));
		$video->tags()->attach($tag("Philosophy"));
		$video->save();
		$video = App\Video::create(json_decode('{"graphic": true, "service": "y", "title": "Dominion (2018) Full Documentary", "widescreen": true, "service_video_id": "ny6aqdFy9SI", "length": 7200, "mature": false}', true));
		$video->tags()->attach($tag("Ethics"));
		$video->tags()->attach($tag("Documentary"));
		$video->tags()->attach($tag("Information"));
		$video->save();
		$video = App\Video::create(json_decode('{"graphic": false, "service": "y", "title": "MEAT IS MURDER | CAMBRIDGE UNIVERSITY DEBATE", "widescreen": true, "service_video_id": "oJ_7xGN-38A", "length": 4574, "mature": false}', true));
		$video->tags()->attach($tag("Ethics"));
		$video->tags()->attach($tag("Speech"));
		$video->tags()->attach($tag("Philosophy"));
		$video->save();
		$video = App\Video::create(json_decode('{"graphic": true, "service": "y", "title": "How Ableism Hurts Animals", "widescreen": true, "service_video_id": "SxBqoqH6RWE", "length": 1474, "mature": false}', true));
		$video->tags()->attach($tag("Ethics"));
		$video->tags()->attach($tag("Information"));
		$video->tags()->attach($tag("Activism"));
		$video->tags()->attach($tag("Philosophy"));
		$video->save();
		$video = App\Video::create(json_decode('{"graphic": false, "service": "y", "title": "How Your Body Transforms On A Vegan Diet", "widescreen": true, "service_video_id": "yKp8-X1zZqo", "length": 635, "mature": false}', true));
		$video->tags()->attach($tag("Health"));
		$video->tags()->attach($tag("Information"));
		$video->save();
		$video = App\Video::create(json_decode('{"graphic": false, "service": "y", "title": "How Your Body Transforms On A Vegan Diet Part 2", "widescreen": true, "service_video_id": "HAaK--L9tDk", "length": 640, "mature": false}', true));
		$video->tags()->attach($tag("Health"));
		$video->tags()->attach($tag("Information"));
		$video->save();
		$video = App\Video::create(json_decode('{"graphic": false, "service": "y", "title": "Philip Wollen - Most Inspiring Speech on Animal Rights!", "widescreen": true, "service_video_id": "vBx7MGIZ1fU", "length": 1207, "mature": false}', true));
		$video->tags()->attach($tag("Ethics"));
		$video->tags()->attach($tag("Inspiring"));
		$video->tags()->attach($tag("Speech"));
		$video->tags()->attach($tag("Recipes"));
		$video->save();
		$video = App\Video::create(json_decode('{"graphic": false, "service": "y", "title": "Environmental Benefits of Veganism | Christian Hextrum | TEDxCardinalNewmanHS", "widescreen": true, "service_video_id": "2bvoJAfjWMM", "length": 457, "mature": false}', true));
		$video->tags()->attach($tag("Environment"));
		$video->tags()->attach($tag("Information"));
		$video->tags()->attach($tag("Speech"));
		$video->save();
		$video = App\Video::create(json_decode('{"graphic": false, "service": "y", "title": "What animals are thinking and feeling, and why it should matter | Carl Safina | TEDxMidAtlantic", "widescreen": true, "service_video_id": "-wkdH_wluhw", "length": 987, "mature": true}', true));
		$video->tags()->attach($tag("Health"));
		$video->tags()->attach($tag("Fitness"));
		$video->tags()->attach($tag("Music"));
		$video->save();
		$video = App\Video::create(json_decode('{"graphic": false, "service": "y", "title": "We Should All Be Vegan | Change My Mind", "widescreen": true, "service_video_id": "zs_UTC9f1YE", "length": 3013, "mature": false}', true));
		$video->tags()->attach($tag("Ethics"));
		$video->tags()->attach($tag("Activism"));
		$video->tags()->attach($tag("Philosophy"));
		$video->save();
		$video = App\Video::create(json_decode('{"graphic": false, "service": "y", "title": "A MESSAGE TO ALL VEGANS", "widescreen": true, "service_video_id": "2igULtwaVA4", "length": 511, "mature": false}', true));
		$video->save();
		$video = App\Video::create(json_decode('{"graphic": false, "service": "y", "title": "Vegan VS Dairy Farmer (Live BBC Debate)", "widescreen": true, "service_video_id": "ykbPLogCJs8", "length": 294, "mature": false}', true));
		$video->save();
		$video = App\Video::create(json_decode('{"graphic": false, "service": "y", "title": "Will We Ever See a Vegan World?", "widescreen": true, "service_video_id": "tawFvfeHhQ0", "length": 226, "mature": false}', true));
		$video->save();
		$video = App\Video::create(json_decode('{"graphic": false, "service": "y", "title": "Vegan Visits UK Pig Farm", "widescreen": true, "service_video_id": "beZolR1nxj8", "length": 269, "mature": false}', true));
		$video->save();
		$video = App\Video::create(json_decode('{"graphic": false, "service": "y", "title": "You Can\'t Love Animals and Eat Them | Change My Mind", "widescreen": true, "service_video_id": "lP3qJ6h0zyI", "length": 1653, "mature": false}', true));
		$video->tags()->attach($tag("Activism"));
		$video->tags()->attach($tag("Speech"));
		$video->tags()->attach($tag("Debate"));
		$video->save();
		$video = App\Video::create(json_decode('{"graphic": false, "service": "y", "title": "You Can\'t Love Animals and Eat Them | Change My Mind Part #2", "widescreen": true, "service_video_id": "PrKAycD7LRo", "length": 2224, "mature": false}', true));
		$video->tags()->attach($tag("Ethics"));
		$video->tags()->attach($tag("Activism"));
		$video->tags()->attach($tag("Speech"));
		$video->tags()->attach($tag("Debate"));
		$video->save();
		$video = App\Video::create(json_decode('{"graphic": false, "service": "y", "title": "EVERY ARGUMENT AGAINST VEGANISM", "widescreen": true, "service_video_id": "RDx0DW8GN_w", "length": 789, "mature": false}', true));
		$video->tags()->attach($tag("Ethics"));
		$video->tags()->attach($tag("Activism"));
		$video->tags()->attach($tag("Speech"));
		$video->tags()->attach($tag("Debate"));
		$video->save();
		$video = App\Video::create(json_decode('{"graphic": true, "service": "y", "title": "The Truth About Backyard Eggs", "widescreen": true, "service_video_id": "GxO2-WREo50", "length": 195, "mature": false}', true));
		$video->tags()->attach($tag("Ethics"));
		$video->tags()->attach($tag("Information"));
		$video->save();
		$video = App\Video::create(json_decode('{"graphic": true, "service": "y", "title": "Egg Industry In 60 Seconds", "widescreen": true, "service_video_id": "B-gSoXwFlIE", "length": 96, "mature": false}', true));
		$video->tags()->attach($tag("Ethics"));
		$video->tags()->attach($tag("Information"));
		$video->save();
		$video = App\Video::create(json_decode('{"graphic": true, "service": "y", "title": "I Can\'t Bring Myself to Watch it", "widescreen": true, "service_video_id": "cWGmvR5uH3k", "length": 126, "mature": false}', true));
		$video->tags()->attach($tag("Inspiring"));
		$video->tags()->attach($tag("Activism"));
		$video->save();
		$video = App\Video::create(json_decode('{"graphic": true, "service": "y", "title": "Dominion Trailer (2018)", "widescreen": true, "service_video_id": "LnpsEAHAEnY", "length": 280, "mature": false}', true));
		$video->tags()->attach($tag("Ethics"));
		$video->tags()->attach($tag("Documentary"));
		$video->save();
		$video = App\Video::create(json_decode('{"graphic": false, "service": "y", "title": "Vegan Communication: The Problem and the Promise - Dr. Melanie Joy", "widescreen": true, "service_video_id": "XfNoiOlef2U", "length": 2699, "mature": false}', true));
		$video->tags()->attach($tag("Information"));
		$video->tags()->attach($tag("Activism"));
		$video->tags()->attach($tag("Speech"));
		$video->save();
		$video = App\Video::create(json_decode('{"graphic": true, "service": "y", "title": "What the Dairy Industry Doesn\'t Want You to Know - Neal Barnard MD - FULL TALK", "widescreen": true, "service_video_id": "h3c_D0s391Q", "length": 3295, "mature": false}', true));
		$video->tags()->attach($tag("Environment"));
		$video->tags()->attach($tag("Information"));
		$video->tags()->attach($tag("Speech"));
		$video->save();
		$video = App\Video::create(json_decode('{"graphic": false, "service": "y", "title": "\"Norm\" - A Short Film", "widescreen": true, "service_video_id": "poxl0K9UrP0", "length": 758, "mature": true}', true));
		$video->tags()->attach($tag("Ethics"));
		$video->tags()->attach($tag("Philosophy"));
		$video->tags()->attach($tag("Sketches"));
		$video->save();
		$video = App\Video::create(json_decode('{"graphic": false, "service": "y", "title": "The Secret Weapon: FOOD MARKETING", "widescreen": true, "service_video_id": "Q5pB-OUEgks", "length": 419, "mature": false}', true));
		$video->tags()->attach($tag("Ethics"));
		$video->tags()->attach($tag("Information"));
		$video->tags()->attach($tag("Speech"));
		$video->tags()->attach($tag("Philosophy"));
		$video->save();
		$video = App\Video::create(json_decode('{"graphic": false, "service": "y", "title": "The Science of Social Change - AR2014", "widescreen": true, "service_video_id": "NWHqJpcgjk0", "length": 1974, "mature": false}', true));
		$video->tags()->attach($tag("Information"));
		$video->save();
		$video = App\Video::create(json_decode('{"graphic": false, "service": "y", "title": "BUDGET FRIENDLY VEGAN GROCERY GUIDE FOR BEGINNERS / Vegan Grocery Haul", "widescreen": true, "service_video_id": "NpPDgrbmAYQ", "length": 1031, "mature": false}', true));
		$video->save();
		$video = App\Video::create(json_decode('{"graphic": false, "service": "y", "title": "Let us be Heroes - The True Cost of our Food Choices (2018) Full documentary", "widescreen": true, "service_video_id": "goBKGTYl2fo", "length": 2467, "mature": false}', true));
		$video->tags()->attach($tag("Environment"));
		$video->tags()->attach($tag("Ethics"));
		$video->tags()->attach($tag("Health"));
		$video->tags()->attach($tag("Documentary"));
		$video->save();
		$video = App\Video::create(json_decode('{"graphic": true, "service": "y", "title": "What You Eat Matters - 2018 Documentary H.O.P.E.", "widescreen": true, "service_video_id": "pDg7tlEJD64", "length": 5547, "mature": false}', true));
		$video->tags()->attach($tag("Environment"));
		$video->tags()->attach($tag("Ethics"));
		$video->tags()->attach($tag("Documentary"));
		$video->save();
		$video = App\Video::create(json_decode('{"graphic": false, "service": "y", "title": "THROUGH VEGAN EYES", "widescreen": true, "service_video_id": "hbwhS7HSOAw", "length": 379, "mature": false}', true));
		$video->tags()->attach($tag("Environment"));
		$video->tags()->attach($tag("Ethics"));
		$video->tags()->attach($tag("Health"));
		$video->tags()->attach($tag("Information"));
		$video->save();
		$video = App\Video::create(json_decode('{"graphic": true, "service": "y", "title": "Beyond the Lies", "widescreen": true, "service_video_id": "OW3y_TztrWw", "length": 287, "mature": false}', true));
		$video->tags()->attach($tag("Ethics"));
		$video->tags()->attach($tag("Documentary"));
		$video->tags()->attach($tag("Undercover"));
		$video->save();
		$video = App\Video::create(json_decode('{"graphic": false, "service": "y", "title": "The Secret Reason We Eat Meat - Dr. Melanie Joy", "widescreen": true, "service_video_id": "ao2GL3NAWQU", "length": 1083, "mature": false}', true));
		$video->save();
		$video = App\Video::create(json_decode('{"graphic": true, "service": "y", "title": "The Wool Industry EXPOSED (What They Don\'t Want You To Know)", "widescreen": true, "service_video_id": "siTvjWE2aVw", "length": 857, "mature": true}', true));
		$video->tags()->attach($tag("Ethics"));
		$video->tags()->attach($tag("Information"));
		$video->save();
		$video = App\Video::create(json_decode('{"graphic": false, "service": "y", "title": "What\'s Wrong With Eggs? The Truth About The Egg Industry \ud83c\udf73", "widescreen": true, "service_video_id": "utPkDP3T7R4", "length": 1273, "mature": false}', true));
		$video->save();
		$video = App\Video::create(json_decode('{"graphic": false, "service": "y", "title": "THE VEGAN PROPHECY | The Journey Begins...", "widescreen": true, "service_video_id": "3Intje_Pb1Y", "length": 1305, "mature": false}', true));
		$video->tags()->attach($tag("Ethics"));
		$video->tags()->attach($tag("Inspiring"));
		$video->tags()->attach($tag("Activism"));
		$video->tags()->attach($tag("Speech"));
		$video->save();
		$video = App\Video::create(json_decode('{"graphic": true, "service": "y", "title": "Lucent (2014) - full documentary", "widescreen": true, "service_video_id": "KArL5YjaL5U", "length": 6401, "mature": false}', true));
		$video->tags()->attach($tag("Documentary"));
		$video->save();
		$video = App\Video::create(json_decode('{"graphic": true, "service": "y", "title": "Land of Hope and Glory (UK \'Earthlings\' Documentary)", "widescreen": true, "service_video_id": "dvtVkNofcq8", "length": 2898, "mature": false}', true));
		$video->tags()->attach($tag("Documentary"));
		$video->save();
		$video = App\Video::create(json_decode('{"graphic": false, "service": "y", "title": "Professor Tom Regan: An Introduction to Animal Rights", "widescreen": true, "service_video_id": "jGyCxnMdpUg", "length": 2995, "mature": false}', true));
		$video->tags()->attach($tag("Ethics"));
		$video->tags()->attach($tag("Speech"));
		$video->save();
		$video = App\Video::create(json_decode('{"graphic": true, "service": "y", "title": "Colleen Patrick-Goudreau: Debunking the Myths of Veganism", "widescreen": true, "service_video_id": "od_cqvr-ueY", "length": 3954, "mature": false}', true));
		$video->tags()->attach($tag("Speech"));
		$video->save();
		$video = App\Video::create(json_decode('{"graphic": false, "service": "y", "title": "Uprooting the Leading Causes of Death", "widescreen": true, "service_video_id": "30gEiweaAVQ", "length": 3349, "mature": false}', true));
		$video->tags()->attach($tag("Health"));
		$video->tags()->attach($tag("Information"));
		$video->tags()->attach($tag("Speech"));
		$video->save();
		$video = App\Video::create(json_decode('{"graphic": false, "service": "y", "title": "The Food Matrix - 101 Reasons to Go Vegan", "widescreen": true, "service_video_id": "YnQb58BoBQw", "length": 4126, "mature": false}', true));
		$video->tags()->attach($tag("Speech"));
		$video->save();
		$video = App\Video::create(json_decode('{"graphic": false, "service": "y", "title": "Why Meat is the Best Worst Thing in the World \ud83c\udf54", "widescreen": true, "service_video_id": "NxvQPzrg2Wg", "length": 528, "mature": false}', true));
		$video->tags()->attach($tag("Environment"));
		$video->tags()->attach($tag("Ethics"));
		$video->tags()->attach($tag("Health"));
		$video->tags()->attach($tag("Information"));
		$video->tags()->attach($tag("Sketches"));
		$video->save();
		$video = App\Video::create(json_decode('{"graphic": false, "service": "y", "title": "Gary Yourofsky Compilation (Russel Brand Awakened Man Sequel)", "widescreen": true, "service_video_id": "0Tih-Lfqt9Q", "length": 779, "mature": false}', true));
		$video->tags()->attach($tag("Ethics"));
		$video->tags()->attach($tag("Inspiring"));
		$video->tags()->attach($tag("Information"));
		$video->tags()->attach($tag("Speech"));
		$video->save();
		$video = App\Video::create(json_decode('{"graphic": true, "service": "y", "title": "Casa de Carne", "widescreen": true, "service_video_id": "c1DcFmUrxUQ", "length": 142, "mature": false}', true));
		$video->tags()->attach($tag("Ethics"));
		$video->tags()->attach($tag("Inspiring"));
		$video->tags()->attach($tag("Activism"));
		$video->tags()->attach($tag("Sketches"));
		$video->save();
		$video = App\Video::create(json_decode('{"graphic": false, "service": "y", "title": "2 Minute Vegan White Sauce (Bechamel), Cheese Sauce or Custard", "widescreen": true, "service_video_id": "Keunf2CKTGs", "length": 317, "mature": true}', true));
		$video->tags()->attach($tag("Environment"));
		$video->tags()->attach($tag("Science"));
		$video->save();
		$video = App\Video::create(json_decode('{"graphic": false, "service": "y", "title": "Patrik Baboumian - World Strongest Man, he\'s VEGAN!", "widescreen": false, "service_video_id": "JeA3EK98TBg", "length": 73, "mature": true}', true));
		$video->tags()->attach($tag("Documentary"));
		$video->tags()->attach($tag("Activism"));
		$video->save();
		$video = App\Video::create(json_decode('{"graphic": true, "service": "y", "title": "40 NON-VEGANS TRICKED to WATCH DOMINION | (Brutal Vegan film 2018 , Episode 1 of 2)", "widescreen": true, "service_video_id": "Ey6eDNJJv_I", "length": 2282, "mature": false}', true));
		$video->tags()->attach($tag("Inspiring"));
		$video->tags()->attach($tag("Information"));
		$video->tags()->attach($tag("Activism"));
		$video->save();
		$video = App\Video::create(json_decode('{"graphic": true, "service": "y", "title": "(EPIC) MEAT EATER VS VEGAN", "widescreen": true, "service_video_id": "ZE29zYwtt8s", "length": 332, "mature": false}', true));
		$video->tags()->attach($tag("Ethics"));
		$video->tags()->attach($tag("Inspiring"));
		$video->tags()->attach($tag("Music"));
		$video->save();
		$video = App\Video::create(json_decode('{"graphic": false, "service": "y", "title": "Tasting the World\u2019s First Test-Tube Steak", "widescreen": true, "service_video_id": "bjSe-0vSRMY", "length": 594, "mature": false}', true));
		$video->tags()->attach($tag("Health"));
		$video->tags()->attach($tag("Information"));
		$video->tags()->attach($tag("Science"));
		$video->save();
		$video = App\Video::create(json_decode('{"graphic": true, "service": "y", "title": "WARNING - Graphic Video: Undercover Video of Bettencourt Dairies in Idaho", "widescreen": true, "service_video_id": "eauq54XScE4", "length": 132, "mature": false}', true));
		$video->tags()->attach($tag("Ethics"));
		$video->tags()->attach($tag("Information"));
		$video->tags()->attach($tag("Undercover"));
		$video->save();
		$video = App\Video::create(json_decode('{"graphic": true, "service": "y", "title": "Undercover Investigation at Hy-Line Hatchery", "widescreen": true, "service_video_id": "JJ--faib7to", "length": 224, "mature": false}', true));
		$video->tags()->attach($tag("Ethics"));
		$video->tags()->attach($tag("Information"));
		$video->tags()->attach($tag("Undercover"));
		$video->save();
		$video = App\Video::create(json_decode('{"graphic": false, "service": "y", "title": "Why Direct Action? A Talk by Wayne Hsiung", "widescreen": true, "service_video_id": "DwjRdfibk7M", "length": 895, "mature": false}', true));
		$video->tags()->attach($tag("Inspiring"));
		$video->tags()->attach($tag("Information"));
		$video->tags()->attach($tag("Activism"));
		$video->save();
		$video = App\Video::create(json_decode('{"graphic": false, "service": "y", "title": "The Save Movement", "widescreen": true, "service_video_id": "TgczQju9sbY", "length": 317, "mature": false}', true));
		$video->tags()->attach($tag("Ethics"));
		$video->tags()->attach($tag("Information"));
		$video->tags()->attach($tag("Activism"));
		$video->save();
		$video = App\Video::create(json_decode('{"graphic": false, "service": "y", "title": "VEGAN WAITER", "widescreen": true, "service_video_id": "NVfGjvZ8WiI", "length": 156, "mature": false}', true));
		$video->tags()->attach($tag("Humor"));
		$video->tags()->attach($tag("Ethics"));
		$video->tags()->attach($tag("Information"));
		$video->tags()->attach($tag("Sketches"));
		$video->save();
		$video = App\Video::create(json_decode('{"graphic": false, "service": "y", "title": "Nebulake - F**k You, I\'m Vegan! (Official Music Video)", "widescreen": true, "service_video_id": "vfX_PnlOShk", "length": 249, "mature": true}', true));
		$video->tags()->attach($tag("Environment"));
		$video->tags()->attach($tag("Inspiring"));
		$video->tags()->attach($tag("Documentary"));
		$video->tags()->attach($tag("Recipes"));
		$video->save();
		$video = App\Video::create(json_decode('{"graphic": false, "service": "y", "title": "Grey - Vegan Thanksgiving (Official Music Video)", "widescreen": true, "service_video_id": "aQv7TMcZ_eE", "length": 195, "mature": false}', true));
		$video->tags()->attach($tag("Humor"));
		$video->tags()->attach($tag("Health"));
		$video->tags()->attach($tag("Inspiring"));
		$video->tags()->attach($tag("Music"));
		$video->save();
		$video = App\Video::create(json_decode('{"graphic": true, "service": "y", "title": "Earthlings Documentary", "widescreen": true, "service_video_id": "ChiGijkR46k", "length": 5747, "mature": false}', true));
		$video->tags()->attach($tag("Ethics"));
		$video->tags()->attach($tag("Documentary"));
		$video->tags()->attach($tag("Information"));
		$video->save();
		$video = App\Video::create(json_decode('{"graphic": false, "service": "y", "title": "This Man Will Inspire You - James Aspey", "widescreen": true, "service_video_id": "a22XxXP3nU8", "length": 601, "mature": false}', true));
		$video->tags()->attach($tag("Ethics"));
		$video->tags()->attach($tag("Inspiring"));
		$video->tags()->attach($tag("Information"));
		$video->tags()->attach($tag("Speech"));
		$video->save();
		$video = App\Video::create(json_decode('{"graphic": false, "service": "y", "title": "Kyle OSullivan \ud83c\udf31Amazing Vegan rap + Lyrics", "widescreen": true, "service_video_id": "HkQTXG0Zd58", "length": 216, "mature": false}', true));
		$video->tags()->attach($tag("Humor"));
		$video->tags()->attach($tag("Inspiring"));
		$video->tags()->attach($tag("Information"));
		$video->tags()->attach($tag("Music"));
		$video->save();
		$video = App\Video::create(json_decode('{"graphic": false, "service": "v", "title": "TESTING VIMEO 2", "widescreen": true, "service_video_id": "230239118", "length": 998, "mature": false}', true));
		$video->tags()->attach($tag("Ethics"));
		$video->tags()->attach($tag("Inspiring"));
		$video->tags()->attach($tag("Information"));
		$video->tags()->attach($tag("Speech"));
		$video->save();
		$video = App\Video::create(json_decode('{"graphic": false, "service": "v", "title": "TESTING VIMEO 1", "widescreen": true, "service_video_id": "218348745", "length": 1443, "mature": false}', true));
		$video->tags()->attach($tag("Humor"));
		$video->tags()->attach($tag("Inspiring"));
		$video->tags()->attach($tag("Information"));
		$video->tags()->attach($tag("Music"));
		$video->save();

	}
}