<?php

    /*  !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! *
     *  !! THIS FILE IS AUTOGENERATED !! *
     *  !! YOU SHOULD PROBABLY NOT BE !! *
     *  !!   MANUALLY EDITING THIS.   !! *
     *  !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! */

    use Illuminate\Database\Migrations\Migration;
    use App\Video;

    class ImportVideos extends Migration
    {

        public function up()
        {

            $tags = App\Tag::all();
            $tagId = function( $name ) use ( $tags ) { return $tags->where( 'name', $name )->first()->id; };

            $video = App\Video::create( json_decode( '{"graphic": false, "service": "y", "title": "Why Meat is the Best Worst Thing in the World", "widescreen": true, "service_video_id": "NxvQPzrg2Wg", "length": 528, "mature": false}', true ) );
            $video->tags()->attach( $tagId( "Environment" ) );
            $video->tags()->attach( $tagId( "Ethics" ) );
            $video->tags()->attach( $tagId( "Health" ) );
            $video->tags()->attach( $tagId( "Information" ) );
            $video->tags()->attach( $tagId( "Sketches" ) );
            $video->save();
            
            $video = App\Video::create( json_decode( '{"graphic": true, "service": "y", "title": "Dairy Is Scary", "widescreen": true, "service_video_id": "UcN7SGGoCNI", "length": 340, "mature": false}', true ) );
            $video->tags()->attach( $tagId( "Environment" ) );
            $video->tags()->attach( $tagId( "Ethics" ) );
            $video->tags()->attach( $tagId( "Health" ) );
            $video->tags()->attach( $tagId( "Information" ) );
            $video->save();
            
            $video = App\Video::create( json_decode( '{"graphic": true, "service": "y", "title": "Undercover Investigation at Hy-Line Hatchery", "widescreen": true, "service_video_id": "JJ--faib7to", "length": 224, "mature": false}', true ) );
            $video->tags()->attach( $tagId( "Ethics" ) );
            $video->tags()->attach( $tagId( "Information" ) );
            $video->tags()->attach( $tagId( "Undercover" ) );
            $video->save();
            
            $video = App\Video::create( json_decode( '{"graphic": false, "service": "y", "title": "You Will Never Look at Your Life in the Same Way Again", "widescreen": true, "service_video_id": "Z3u7hXpOm58", "length": 1942, "mature": false}', true ) );
            $video->tags()->attach( $tagId( "Ethics" ) );
            $video->tags()->attach( $tagId( "Inspiring" ) );
            $video->tags()->attach( $tagId( "Information" ) );
            $video->tags()->attach( $tagId( "Speech" ) );
            $video->save();
            
            $video = App\Video::create( json_decode( '{"graphic": false, "service": "y", "title": "Tasting the World\u2019s First Test-Tube Steak", "widescreen": true, "service_video_id": "bjSe-0vSRMY", "length": 594, "mature": false}', true ) );
            $video->tags()->attach( $tagId( "Health" ) );
            $video->tags()->attach( $tagId( "Information" ) );
            $video->tags()->attach( $tagId( "Science" ) );
            $video->save();
            
            $video = App\Video::create( json_decode( '{"graphic": false, "service": "y", "title": "Beginners Guide to Veganism", "widescreen": true, "service_video_id": "OJxMsypwnqg", "length": 721, "mature": false}', true ) );
            $video->tags()->attach( $tagId( "Health" ) );
            $video->tags()->attach( $tagId( "Information" ) );
            $video->tags()->attach( $tagId( "Recipes" ) );
            $video->tags()->attach( $tagId( "Guides" ) );
            $video->save();
            
            $video = App\Video::create( json_decode( '{"graphic": false, "service": "y", "title": "EASY VEGAN RECIPES FOR LAZY PEOPLE (10 minute dinners)", "widescreen": true, "service_video_id": "3AUo5zja1-0", "length": 650, "mature": false}', true ) );
            $video->tags()->attach( $tagId( "Recipes" ) );
            $video->save();
            
            $video = App\Video::create( json_decode( '{"graphic": false, "service": "y", "title": "VEGAN 2017 - The Film", "widescreen": true, "service_video_id": "IxVR53xemSs", "length": 2820, "mature": false}', true ) );
            $video->tags()->attach( $tagId( "Inspiring" ) );
            $video->tags()->attach( $tagId( "Information" ) );
            $video->tags()->attach( $tagId( "News" ) );
            $video->save();
            
            $video = App\Video::create( json_decode( '{"graphic": false, "service": "y", "title": "Uprooting the Leading Causes of Death", "widescreen": true, "service_video_id": "30gEiweaAVQ", "length": 3349, "mature": false}', true ) );
            $video->tags()->attach( $tagId( "Health" ) );
            $video->tags()->attach( $tagId( "Information" ) );
            $video->tags()->attach( $tagId( "Speech" ) );
            $video->save();
            
            $video = App\Video::create( json_decode( '{"graphic": true, "service": "y", "title": "Casa de Carne", "widescreen": true, "service_video_id": "c1DcFmUrxUQ", "length": 142, "mature": false}', true ) );
            $video->tags()->attach( $tagId( "Ethics" ) );
            $video->tags()->attach( $tagId( "Inspiring" ) );
            $video->tags()->attach( $tagId( "Activism" ) );
            $video->tags()->attach( $tagId( "Sketches" ) );
            $video->save();
            
            $video = App\Video::create( json_decode( '{"graphic": false, "service": "y", "title": "How Your Body Transforms On a Vegan Diet (Part 1)", "widescreen": true, "service_video_id": "yKp8-X1zZqo", "length": 635, "mature": false}', true ) );
            $video->tags()->attach( $tagId( "Health" ) );
            $video->tags()->attach( $tagId( "Information" ) );
            $video->save();
            
            $video = App\Video::create( json_decode( '{"graphic": false, "service": "y", "title": "How to make Tofu look and taste like Chicken", "widescreen": true, "service_video_id": "LwDYQxdc5_Q", "length": 369, "mature": false}', true ) );
            $video->tags()->attach( $tagId( "Recipes" ) );
            $video->save();
            
            $video = App\Video::create( json_decode( '{"graphic": false, "service": "y", "title": "MEAL PREP FOR THE WEEK FOR $20 (VEGAN + EASY)", "widescreen": true, "service_video_id": "j3eYVEyMpTY", "length": 843, "mature": false}', true ) );
            $video->tags()->attach( $tagId( "Recipes" ) );
            $video->save();
            
            $video = App\Video::create( json_decode( '{"graphic": false, "service": "y", "title": "What\'s Wrong With Eggs? The Truth About The Egg Industry", "widescreen": true, "service_video_id": "utPkDP3T7R4", "length": 1273, "mature": false}', true ) );
            $video->save();
            
            $video = App\Video::create( json_decode( '{"graphic": false, "service": "y", "title": "Tofucken: The Vegan Turducken", "widescreen": true, "service_video_id": "j5QAjcbvbDg", "length": 139, "mature": false}', true ) );
            $video->tags()->attach( $tagId( "Humor" ) );
            $video->tags()->attach( $tagId( "Recipes" ) );
            $video->save();
            
            $video = App\Video::create( json_decode( '{"graphic": false, "service": "y", "title": "VEGAN MEAL PREP FOR $20 (FULL WEEK OF FOOD!)", "widescreen": true, "service_video_id": "Js8sM0XA2sk", "length": 1076, "mature": false}', true ) );
            $video->tags()->attach( $tagId( "Recipes" ) );
            $video->save();
            
            $video = App\Video::create( json_decode( '{"graphic": true, "service": "y", "title": "What the Dairy Industry Doesn\'t Want You to Know", "widescreen": true, "service_video_id": "h3c_D0s391Q", "length": 3295, "mature": false}', true ) );
            $video->tags()->attach( $tagId( "Environment" ) );
            $video->tags()->attach( $tagId( "Information" ) );
            $video->tags()->attach( $tagId( "Speech" ) );
            $video->save();
            
            $video = App\Video::create( json_decode( '{"graphic": false, "service": "y", "title": "VEGAN FOOD HACKS YOU NEED TO KNOW", "widescreen": true, "service_video_id": "vsVFqy9bF84", "length": 512, "mature": false}', true ) );
            $video->tags()->attach( $tagId( "Recipes" ) );
            $video->save();
            
            $video = App\Video::create( json_decode( '{"graphic": false, "service": "y", "title": "Wha Me Eat - Macka B", "widescreen": true, "service_video_id": "FLqjLn0W5K0", "length": 285, "mature": false}', true ) );
            $video->tags()->attach( $tagId( "Music" ) );
            $video->save();
            
            $video = App\Video::create( json_decode( '{"graphic": false, "service": "y", "title": "The Secret Reason We Eat Meat", "widescreen": true, "service_video_id": "ao2GL3NAWQU", "length": 1083, "mature": false}', true ) );
            $video->save();
            
            $video = App\Video::create( json_decode( '{"graphic": false, "service": "y", "title": "How To Prevent Deficiencies On A Vegan Diet", "widescreen": true, "service_video_id": "zKwnMCEp3HM", "length": 844, "mature": false}', true ) );
            $video->tags()->attach( $tagId( "Health" ) );
            $video->tags()->attach( $tagId( "Information" ) );
            $video->tags()->attach( $tagId( "Recipes" ) );
            $video->tags()->attach( $tagId( "Science" ) );
            $video->save();
            
            $video = App\Video::create( json_decode( '{"graphic": false, "service": "y", "title": "What Drinking 1.5 GALLONS OF WATER A DAY FOR 2 WEEKS did to me", "widescreen": true, "service_video_id": "g3k8kzwqmTg", "length": 781, "mature": false}', true ) );
            $video->tags()->attach( $tagId( "Recipes" ) );
            $video->save();
            
            $video = App\Video::create( json_decode( '{"graphic": false, "service": "y", "title": "Advice for New Vegans! (B12, Protein and more)", "widescreen": true, "service_video_id": "OGoZ-oJjy7U", "length": 776, "mature": false}', true ) );
            $video->tags()->attach( $tagId( "Health" ) );
            $video->tags()->attach( $tagId( "Fitness" ) );
            $video->save();
            
            $video = App\Video::create( json_decode( '{"graphic": true, "service": "y", "title": "HOPE - What You Eat Matters", "widescreen": true, "service_video_id": "pDg7tlEJD64", "length": 5547, "mature": false}', true ) );
            $video->tags()->attach( $tagId( "Environment" ) );
            $video->tags()->attach( $tagId( "Ethics" ) );
            $video->tags()->attach( $tagId( "Documentary" ) );
            $video->save();
            
            $video = App\Video::create( json_decode( '{"graphic": false, "service": "y", "title": "Vegans: twenty one pilots parody - Heathens", "widescreen": true, "service_video_id": "FmwIB-8Eebg", "length": 226, "mature": false}', true ) );
            $video->tags()->attach( $tagId( "Humor" ) );
            $video->tags()->attach( $tagId( "Music" ) );
            $video->save();
            
            $video = App\Video::create( json_decode( '{"graphic": false, "service": "y", "title": "How to Cook Tofu Like a BOSS (BEGINNER\'S GUIDE TO TOFU)", "widescreen": true, "service_video_id": "HhQqfw8UAUY", "length": 1426, "mature": false}', true ) );
            $video->tags()->attach( $tagId( "Recipes" ) );
            $video->save();
            
            $video = App\Video::create( json_decode( '{"graphic": false, "service": "y", "title": "Vegan Full Day of Eating & Training On a Cut #1", "widescreen": true, "service_video_id": "sVdT1AxN2PA", "length": 623, "mature": false}', true ) );
            $video->tags()->attach( $tagId( "Health" ) );
            $video->tags()->attach( $tagId( "Fitness" ) );
            $video->save();
            
            $video = App\Video::create( json_decode( '{"graphic": false, "service": "y", "title": "Vegan Full Day Of Eating | Vegan Athlete", "widescreen": true, "service_video_id": "l5dnOxTwobE", "length": 393, "mature": false}', true ) );
            $video->tags()->attach( $tagId( "Health" ) );
            $video->tags()->attach( $tagId( "Fitness" ) );
            $video->save();
            
            $video = App\Video::create( json_decode( '{"graphic": false, "service": "y", "title": "VEGAN Bodybuilding & Diet - THE TRUTH", "widescreen": true, "service_video_id": "GR_XfQ4je9s", "length": 767, "mature": false}', true ) );
            $video->tags()->attach( $tagId( "Health" ) );
            $video->tags()->attach( $tagId( "Fitness" ) );
            $video->save();
            
            $video = App\Video::create( json_decode( '{"graphic": true, "service": "y", "title": "Lucent Documentary", "widescreen": true, "service_video_id": "KArL5YjaL5U", "length": 6401, "mature": false}', true ) );
            $video->tags()->attach( $tagId( "Documentary" ) );
            $video->save();
            
            $video = App\Video::create( json_decode( '{"graphic": false, "service": "y", "title": "VEGAN 2018 - The Film", "widescreen": true, "service_video_id": "bTeqU6_Jryc", "length": 3460, "mature": false}', true ) );
            $video->tags()->attach( $tagId( "Inspiring" ) );
            $video->tags()->attach( $tagId( "Information" ) );
            $video->tags()->attach( $tagId( "News" ) );
            $video->save();
            
            $video = App\Video::create( json_decode( '{"graphic": false, "service": "y", "title": "The Best Vegan Carbonara - 15 mins", "widescreen": true, "service_video_id": "jR9KTsiU9-o", "length": 236, "mature": false}', true ) );
            $video->tags()->attach( $tagId( "Recipes" ) );
            $video->save();
            
            $video = App\Video::create( json_decode( '{"graphic": false, "service": "y", "title": "The Most Important Speech You Will Ever Hear", "widescreen": true, "service_video_id": "U5hGQDLprA8", "length": 4164, "mature": false}', true ) );
            $video->tags()->attach( $tagId( "Ethics" ) );
            $video->tags()->attach( $tagId( "Inspiring" ) );
            $video->tags()->attach( $tagId( "Information" ) );
            $video->tags()->attach( $tagId( "Speech" ) );
            $video->save();
            
            $video = App\Video::create( json_decode( '{"graphic": false, "service": "y", "title": "Full Day of Eating Vegan | Shoulders and Triceps Workout", "widescreen": true, "service_video_id": "lRQglqJ9hKA", "length": 515, "mature": false}', true ) );
            $video->tags()->attach( $tagId( "Health" ) );
            $video->tags()->attach( $tagId( "Fitness" ) );
            $video->save();
            
            $video = App\Video::create( json_decode( '{"graphic": false, "service": "y", "title": "VEGAN 2016 - The Film", "widescreen": true, "service_video_id": "scsfO9BcB-w", "length": 2104, "mature": false}', true ) );
            $video->tags()->attach( $tagId( "Inspiring" ) );
            $video->tags()->attach( $tagId( "Information" ) );
            $video->tags()->attach( $tagId( "News" ) );
            $video->save();
            
            $video = App\Video::create( json_decode( '{"graphic": false, "service": "y", "title": "VEGAN GROCERY GUIDE | Cheap Lazy Vegan", "widescreen": true, "service_video_id": "IqoggNSvrUc", "length": 751, "mature": false}', true ) );
            $video->tags()->attach( $tagId( "Recipes" ) );
            $video->save();
            
            $video = App\Video::create( json_decode( '{"graphic": true, "service": "y", "title": "Dominion Trailer (2018)", "widescreen": true, "service_video_id": "LnpsEAHAEnY", "length": 280, "mature": false}', true ) );
            $video->tags()->attach( $tagId( "Ethics" ) );
            $video->tags()->attach( $tagId( "Documentary" ) );
            $video->save();
            
            $video = App\Video::create( json_decode( '{"graphic": false, "service": "y", "title": "What I Eat In a Day As A Vegan Bodybuilder", "widescreen": true, "service_video_id": "3HtyehGHnBE", "length": 697, "mature": false}', true ) );
            $video->tags()->attach( $tagId( "Health" ) );
            $video->tags()->attach( $tagId( "Fitness" ) );
            $video->save();
            
            $video = App\Video::create( json_decode( '{"graphic": false, "service": "y", "title": "What Animals Are Thinking and Feeling, and Why it Should Matter", "widescreen": true, "service_video_id": "-wkdH_wluhw", "length": 987, "mature": false}', true ) );
            $video->tags()->attach( $tagId( "Ethics" ) );
            $video->tags()->attach( $tagId( "Information" ) );
            $video->tags()->attach( $tagId( "Speech" ) );
            $video->save();
            
            $video = App\Video::create( json_decode( '{"graphic": false, "service": "y", "title": "VEGAN 2015 - The Film", "widescreen": true, "service_video_id": "BYzlfPdpAeY", "length": 1432, "mature": false}', true ) );
            $video->tags()->attach( $tagId( "Inspiring" ) );
            $video->tags()->attach( $tagId( "Information" ) );
            $video->tags()->attach( $tagId( "News" ) );
            $video->save();
            
            $video = App\Video::create( json_decode( '{"graphic": false, "service": "y", "title": "Quick & Simple Vegan Omelettes (with GF option)", "widescreen": true, "service_video_id": "q3xs_175vUM", "length": 349, "mature": false}', true ) );
            $video->tags()->attach( $tagId( "Recipes" ) );
            $video->save();
            
            $video = App\Video::create( json_decode( '{"graphic": false, "service": "y", "title": "James Wildman - 101 Reasons to Go Vegan", "widescreen": true, "service_video_id": "YnQb58BoBQw", "length": 4126, "mature": false}', true ) );
            $video->tags()->attach( $tagId( "Speech" ) );
            $video->save();
            
            $video = App\Video::create( json_decode( '{"graphic": false, "service": "y", "title": "Grey - Vegan Thanksgiving (Official Music Video)", "widescreen": true, "service_video_id": "aQv7TMcZ_eE", "length": 195, "mature": false}', true ) );
            $video->tags()->attach( $tagId( "Humor" ) );
            $video->tags()->attach( $tagId( "Health" ) );
            $video->tags()->attach( $tagId( "Inspiring" ) );
            $video->tags()->attach( $tagId( "Music" ) );
            $video->save();
            
            $video = App\Video::create( json_decode( '{"graphic": true, "service": "y", "title": "Land of Hope and Glory", "widescreen": true, "service_video_id": "dvtVkNofcq8", "length": 2898, "mature": false}', true ) );
            $video->tags()->attach( $tagId( "Documentary" ) );
            $video->save();
            
            $video = App\Video::create( json_decode( '{"graphic": false, "service": "y", "title": "Kyle OSullivan Amazing Vegan rap + Lyrics", "widescreen": true, "service_video_id": "HkQTXG0Zd58", "length": 216, "mature": false}', true ) );
            $video->tags()->attach( $tagId( "Humor" ) );
            $video->tags()->attach( $tagId( "Inspiring" ) );
            $video->tags()->attach( $tagId( "Information" ) );
            $video->tags()->attach( $tagId( "Music" ) );
            $video->tags()->attach( $tagId( "Arguments" ) );
            $video->save();
            
            $video = App\Video::create( json_decode( '{"graphic": false, "service": "y", "title": "Vegan BodyBuilding | Top 5 Tips For Building Muscle", "widescreen": true, "service_video_id": "eYDDAhooum4", "length": 319, "mature": false}', true ) );
            $video->tags()->attach( $tagId( "Health" ) );
            $video->tags()->attach( $tagId( "Fitness" ) );
            $video->save();
            
            $video = App\Video::create( json_decode( '{"graphic": false, "service": "y", "title": "World\'s BEST Vegan Bacon! (made from tofu)", "widescreen": true, "service_video_id": "DcFAeNNLsNo", "length": 334, "mature": false}', true ) );
            $video->tags()->attach( $tagId( "Recipes" ) );
            $video->save();
            
            $video = App\Video::create( json_decode( '{"graphic": false, "service": "y", "title": "EVERY ARGUMENT AGAINST VEGANISM", "widescreen": true, "service_video_id": "RDx0DW8GN_w", "length": 789, "mature": false}', true ) );
            $video->tags()->attach( $tagId( "Ethics" ) );
            $video->tags()->attach( $tagId( "Activism" ) );
            $video->tags()->attach( $tagId( "Speech" ) );
            $video->tags()->attach( $tagId( "Debate" ) );
            $video->save();
            
            $video = App\Video::create( json_decode( '{"graphic": false, "service": "y", "title": "How to: Vegan Breakfast & Lunch | Cheap Lazy Vegan", "widescreen": true, "service_video_id": "DRIP-nyNKMI", "length": 198, "mature": false}', true ) );
            $video->tags()->attach( $tagId( "Recipes" ) );
            $video->save();
            
            $video = App\Video::create( json_decode( '{"graphic": false, "service": "y", "title": "VEGAN DIET: Dispelling The Biggest Myths", "widescreen": true, "service_video_id": "zV9XhX_QSjA", "length": 1343, "mature": false}', true ) );
            $video->save();
            
            $video = App\Video::create( json_decode( '{"graphic": true, "service": "v", "title": "Thousand Eyes - Australian Animal Agriculture", "widescreen": true, "service_video_id": "130694373", "length": 253, "mature": false}', true ) );
            $video->tags()->attach( $tagId( "Ethics" ) );
            $video->tags()->attach( $tagId( "Documentary" ) );
            $video->tags()->attach( $tagId( "Undercover" ) );
            $video->save();
            
            $video = App\Video::create( json_decode( '{"graphic": true, "service": "y", "title": "The Wool Industry EXPOSED (What They Don\'t Want You To Know)", "widescreen": true, "service_video_id": "siTvjWE2aVw", "length": 857, "mature": true}', true ) );
            $video->tags()->attach( $tagId( "Ethics" ) );
            $video->tags()->attach( $tagId( "Information" ) );
            $video->save();
            
            $video = App\Video::create( json_decode( '{"graphic": false, "service": "y", "title": "Let Us Be Heroes", "widescreen": true, "service_video_id": "goBKGTYl2fo", "length": 2467, "mature": false}', true ) );
            $video->tags()->attach( $tagId( "Environment" ) );
            $video->tags()->attach( $tagId( "Ethics" ) );
            $video->tags()->attach( $tagId( "Health" ) );
            $video->tags()->attach( $tagId( "Documentary" ) );
            $video->save();
            
            $video = App\Video::create( json_decode( '{"graphic": false, "service": "y", "title": "Vegan \'Flaky\' Fish & Chips", "widescreen": true, "service_video_id": "TcJoUZAtITI", "length": 475, "mature": false}', true ) );
            $video->tags()->attach( $tagId( "Recipes" ) );
            $video->save();
            
            $video = App\Video::create( json_decode( '{"graphic": false, "service": "y", "title": "VEGAN HACKS // MUST TRY 5 INGREDIENT RECIPES", "widescreen": true, "service_video_id": "TCsydgDEReY", "length": 451, "mature": false}', true ) );
            $video->tags()->attach( $tagId( "Recipes" ) );
            $video->save();
            
            $video = App\Video::create( json_decode( '{"graphic": false, "service": "y", "title": "Super-Tasty Portobello Mushroom Burgers - 10 min prep", "widescreen": true, "service_video_id": "bPQVt41GFcc", "length": 343, "mature": false}', true ) );
            $video->tags()->attach( $tagId( "Recipes" ) );
            $video->save();
            
            $video = App\Video::create( json_decode( '{"graphic": false, "service": "y", "title": "10 EASY DIY NATURAL BEAUTY HACKS YOU NEED TO TRY!", "widescreen": true, "service_video_id": "fqOnqu6u9a4", "length": 504, "mature": false}', true ) );
            $video->tags()->attach( $tagId( "Cosmetics" ) );
            $video->save();
            
            $video = App\Video::create( json_decode( '{"graphic": false, "service": "y", "title": "The Science of Vegan Fat Loss", "widescreen": true, "service_video_id": "bcN2HjOutEk", "length": 650, "mature": false}', true ) );
            $video->tags()->attach( $tagId( "Health" ) );
            $video->tags()->attach( $tagId( "Information" ) );
            $video->tags()->attach( $tagId( "Science" ) );
            $video->save();
            
            $video = App\Video::create( json_decode( '{"graphic": false, "service": "y", "title": "Chokeules - 40-Year-Old Vegan", "widescreen": true, "service_video_id": "-n-SfgK3ITc", "length": 158, "mature": false}', true ) );
            $video->tags()->attach( $tagId( "Music" ) );
            $video->save();
            
            $video = App\Video::create( json_decode( '{"graphic": false, "service": "y", "title": "How Your Body Transforms On a Vegan Diet (Part 2)", "widescreen": true, "service_video_id": "HAaK--L9tDk", "length": 640, "mature": false}', true ) );
            $video->tags()->attach( $tagId( "Health" ) );
            $video->tags()->attach( $tagId( "Information" ) );
            $video->save();
            
            $video = App\Video::create( json_decode( '{"graphic": false, "service": "y", "title": "Why Vegan?", "widescreen": true, "service_video_id": "y2k4NHjAP84", "length": 288, "mature": false}', true ) );
            $video->tags()->attach( $tagId( "Environment" ) );
            $video->tags()->attach( $tagId( "Ethics" ) );
            $video->tags()->attach( $tagId( "Information" ) );
            $video->save();
            
            $video = App\Video::create( json_decode( '{"graphic": false, "service": "y", "title": "Do you want to make history?", "widescreen": true, "service_video_id": "E6ehL18rqlM", "length": 94, "mature": false}', true ) );
            $video->tags()->attach( $tagId( "Ethics" ) );
            $video->tags()->attach( $tagId( "Documentary" ) );
            $video->save();
            
            $video = App\Video::create( json_decode( '{"graphic": false, "service": "y", "title": "We Should All Be Vegan | Change My Mind | Earthling Ed", "widescreen": true, "service_video_id": "zs_UTC9f1YE", "length": 3013, "mature": false}', true ) );
            $video->tags()->attach( $tagId( "Ethics" ) );
            $video->tags()->attach( $tagId( "Activism" ) );
            $video->save();
            
            $video = App\Video::create( json_decode( '{"graphic": true, "service": "y", "title": "Dominion Documentary (2018)", "widescreen": true, "service_video_id": "ny6aqdFy9SI", "length": 7200, "mature": false}', true ) );
            $video->tags()->attach( $tagId( "Ethics" ) );
            $video->tags()->attach( $tagId( "Documentary" ) );
            $video->tags()->attach( $tagId( "Information" ) );
            $video->save();
            
            $video = App\Video::create( json_decode( '{"graphic": false, "service": "y", "title": "Vegan VS Dairy Farmer (Live BBC Debate)", "widescreen": true, "service_video_id": "ykbPLogCJs8", "length": 294, "mature": false}', true ) );
            $video->tags()->attach( $tagId( "Ethics" ) );
            $video->tags()->attach( $tagId( "Debate" ) );
            $video->save();
            
            $video = App\Video::create( json_decode( '{"graphic": false, "service": "y", "title": "Top 7 Tips For BULKING On A Vegan Diet", "widescreen": true, "service_video_id": "I16QRvehE3E", "length": 715, "mature": false}', true ) );
            $video->tags()->attach( $tagId( "Health" ) );
            $video->tags()->attach( $tagId( "Fitness" ) );
            $video->save();
            
            $video = App\Video::create( json_decode( '{"graphic": false, "service": "y", "title": "\"Norm\" - A Short Film", "widescreen": true, "service_video_id": "poxl0K9UrP0", "length": 758, "mature": true}', true ) );
            $video->tags()->attach( $tagId( "Ethics" ) );
            $video->tags()->attach( $tagId( "Sketches" ) );
            $video->save();
            
            $video = App\Video::create( json_decode( '{"graphic": false, "service": "y", "title": "GUIDE TO VEGAN BODYBUILDING", "widescreen": true, "service_video_id": "zkwX7eRHCQ0", "length": 1311, "mature": false}', true ) );
            $video->tags()->attach( $tagId( "Health" ) );
            $video->tags()->attach( $tagId( "Fitness" ) );
            $video->tags()->attach( $tagId( "Guides" ) );
            $video->save();
            
            $video = App\Video::create( json_decode( '{"graphic": false, "service": "y", "title": "2 Minute Vegan White Sauce (Bechamel), Cheese Sauce or Custard", "widescreen": true, "service_video_id": "Keunf2CKTGs", "length": 317, "mature": false}', true ) );
            $video->tags()->attach( $tagId( "Humor" ) );
            $video->tags()->attach( $tagId( "Recipes" ) );
            $video->save();
            
            $video = App\Video::create( json_decode( '{"graphic": false, "service": "y", "title": "How To Talk To Non-Vegans", "widescreen": true, "service_video_id": "PxCF_8sY54o", "length": 539, "mature": false}', true ) );
            $video->tags()->attach( $tagId( "Ethics" ) );
            $video->tags()->attach( $tagId( "Information" ) );
            $video->tags()->attach( $tagId( "Activism" ) );
            $video->save();
            
            $video = App\Video::create( json_decode( '{"graphic": false, "service": "y", "title": "CAN VEGAN SNICKERS CURE DEPRESSION? II Diet & Depression", "widescreen": true, "service_video_id": "oQiwKt8VSEQ", "length": 451, "mature": false}', true ) );
            $video->tags()->attach( $tagId( "Recipes" ) );
            $video->save();
            
            $video = App\Video::create( json_decode( '{"graphic": false, "service": "y", "title": "Gary Yourofsky Compilation (Russel Brand Awakened Man Sequel)", "widescreen": true, "service_video_id": "0Tih-Lfqt9Q", "length": 779, "mature": false}', true ) );
            $video->tags()->attach( $tagId( "Ethics" ) );
            $video->tags()->attach( $tagId( "Inspiring" ) );
            $video->tags()->attach( $tagId( "Information" ) );
            $video->tags()->attach( $tagId( "Speech" ) );
            $video->save();
            
            $video = App\Video::create( json_decode( '{"graphic": false, "service": "y", "title": "BIG FAT Vegan Cookies in just 15 mins!", "widescreen": true, "service_video_id": "6icvhTifVYo", "length": 76, "mature": false}', true ) );
            $video->tags()->attach( $tagId( "Recipes" ) );
            $video->save();
            
            $video = App\Video::create( json_decode( '{"graphic": false, "service": "y", "title": "WHAT I ATE TODAY AS A VEGAN BODYBUILDER", "widescreen": true, "service_video_id": "a5aUGCNacU0", "length": 782, "mature": false}', true ) );
            $video->tags()->attach( $tagId( "Health" ) );
            $video->tags()->attach( $tagId( "Fitness" ) );
            $video->save();
            
            $video = App\Video::create( json_decode( '{"graphic": false, "service": "y", "title": "Vegan Parmesan in just 2 minutes!!!", "widescreen": true, "service_video_id": "q4h8irQXIX4", "length": 75, "mature": false}', true ) );
            $video->tags()->attach( $tagId( "Recipes" ) );
            $video->save();
            
            $video = App\Video::create( json_decode( '{"graphic": false, "service": "y", "title": "Compassionate Living - Through Vegan Eyes", "widescreen": true, "service_video_id": "hbwhS7HSOAw", "length": 379, "mature": false}', true ) );
            $video->tags()->attach( $tagId( "Environment" ) );
            $video->tags()->attach( $tagId( "Ethics" ) );
            $video->tags()->attach( $tagId( "Health" ) );
            $video->tags()->attach( $tagId( "Information" ) );
            $video->save();
            
            $video = App\Video::create( json_decode( '{"graphic": false, "service": "y", "title": "Chocolate Caramel Cakes! Awesome! Vegan!", "widescreen": true, "service_video_id": "uOvS96gMEow", "length": 310, "mature": false}', true ) );
            $video->tags()->attach( $tagId( "Recipes" ) );
            $video->save();
            
            $video = App\Video::create( json_decode( '{"graphic": false, "service": "y", "title": "Heated Debate on Veganism Outside of a Slaughterhouse", "widescreen": true, "service_video_id": "Exz5BfrMdnw", "length": 4033, "mature": false}', true ) );
            $video->tags()->attach( $tagId( "Debate" ) );
            $video->save();
            
            $video = App\Video::create( json_decode( '{"graphic": false, "service": "y", "title": "Budget friendly vegan grocery guide", "widescreen": true, "service_video_id": "NpPDgrbmAYQ", "length": 1031, "mature": false}', true ) );
            $video->tags()->attach( $tagId( "Guides" ) );
            $video->save();
            
            $video = App\Video::create( json_decode( '{"graphic": false, "service": "y", "title": "You Can\'t Love Animals and Eat Them | Change My Mind (Part 1)", "widescreen": true, "service_video_id": "lP3qJ6h0zyI", "length": 1653, "mature": false}', true ) );
            $video->tags()->attach( $tagId( "Activism" ) );
            $video->tags()->attach( $tagId( "Speech" ) );
            $video->tags()->attach( $tagId( "Debate" ) );
            $video->save();
            
            $video = App\Video::create( json_decode( '{"graphic": false, "service": "y", "title": "VEGAN MEAL PREP FOR MUSCLE | EASY HIGH PROTEIN MEALS", "widescreen": true, "service_video_id": "5dooOnuFyd8", "length": 662, "mature": false}', true ) );
            $video->tags()->attach( $tagId( "Health" ) );
            $video->tags()->attach( $tagId( "Fitness" ) );
            $video->save();
            
            $video = App\Video::create( json_decode( '{"graphic": true, "service": "y", "title": "Vegan Visits UK Dairy Farm", "widescreen": true, "service_video_id": "Ryz98loNvKo", "length": 264, "mature": false}', true ) );
            $video->tags()->attach( $tagId( "Activism" ) );
            $video->save();
            
            $video = App\Video::create( json_decode( '{"graphic": false, "service": "y", "title": "Easy Vegan Sticky Toffee Pudding", "widescreen": true, "service_video_id": "FP73vK852ig", "length": 315, "mature": false}', true ) );
            $video->tags()->attach( $tagId( "Recipes" ) );
            $video->save();
            
            $video = App\Video::create( json_decode( '{"graphic": false, "service": "y", "title": "Vegan Transformation | 70 to 90 kg", "widescreen": true, "service_video_id": "bKNlnuaw6BA", "length": 699, "mature": false}', true ) );
            $video->tags()->attach( $tagId( "Health" ) );
            $video->tags()->attach( $tagId( "Fitness" ) );
            $video->save();
            
            $video = App\Video::create( json_decode( '{"graphic": false, "service": "y", "title": "Vegan Takes on Venice Beach (Part 1)", "widescreen": true, "service_video_id": "0trBUN0V49I", "length": 676, "mature": false}', true ) );
            $video->tags()->attach( $tagId( "Debate" ) );
            $video->save();
            
            $video = App\Video::create( json_decode( '{"graphic": false, "service": "y", "title": "Complete Guide To Vegan Cosmetics", "widescreen": true, "service_video_id": "_oXC9Gb4xL8", "length": 347, "mature": false}', true ) );
            $video->tags()->attach( $tagId( "Cosmetics" ) );
            $video->save();
            
            $video = App\Video::create( json_decode( '{"graphic": false, "service": "y", "title": "Nebulake - F**k You, I\'m Vegan! (Official Music Video)", "widescreen": true, "service_video_id": "vfX_PnlOShk", "length": 249, "mature": false}', true ) );
            $video->tags()->attach( $tagId( "Humor" ) );
            $video->tags()->attach( $tagId( "Health" ) );
            $video->tags()->attach( $tagId( "Inspiring" ) );
            $video->tags()->attach( $tagId( "Music" ) );
            $video->save();
            
            $video = App\Video::create( json_decode( '{"graphic": false, "service": "y", "title": "A MESSAGE TO ALL VEGANS", "widescreen": true, "service_video_id": "2igULtwaVA4", "length": 511, "mature": false}', true ) );
            $video->tags()->attach( $tagId( "Inspiring" ) );
            $video->tags()->attach( $tagId( "Guides" ) );
            $video->save();
            
            $video = App\Video::create( json_decode( '{"graphic": true, "service": "y", "title": "Egg Industry In 60 Seconds", "widescreen": true, "service_video_id": "B-gSoXwFlIE", "length": 96, "mature": false}', true ) );
            $video->tags()->attach( $tagId( "Ethics" ) );
            $video->tags()->attach( $tagId( "Information" ) );
            $video->save();
            
            $video = App\Video::create( json_decode( '{"graphic": true, "service": "y", "title": "Debunking the Myths of Veganism", "widescreen": true, "service_video_id": "od_cqvr-ueY", "length": 3954, "mature": false}', true ) );
            $video->tags()->attach( $tagId( "Speech" ) );
            $video->save();
            
            $video = App\Video::create( json_decode( '{"graphic": false, "service": "y", "title": "Tom Selleck sucks at making Vegan Magnum Ice Creams!", "widescreen": true, "service_video_id": "fEla860FBeQ", "length": 247, "mature": false}', true ) );
            $video->tags()->attach( $tagId( "Recipes" ) );
            $video->save();
            
            $video = App\Video::create( json_decode( '{"graphic": false, "service": "y", "title": "\"No Beef\" (VEGAN RAP) by DISL Automatic ft. TK The Artist", "widescreen": true, "service_video_id": "6sRHAJa-oGE", "length": 235, "mature": false}', true ) );
            $video->tags()->attach( $tagId( "Music" ) );
            $video->save();
            
            $video = App\Video::create( json_decode( '{"graphic": false, "service": "y", "title": "Meat is Murder | Cambridge University Debate", "widescreen": true, "service_video_id": "oJ_7xGN-38A", "length": 4574, "mature": false}', true ) );
            $video->tags()->attach( $tagId( "Ethics" ) );
            $video->tags()->attach( $tagId( "Speech" ) );
            $video->save();
            
            $video = App\Video::create( json_decode( '{"graphic": false, "service": "y", "title": "How I Eat/Train 1 Week Out | Chest Workout", "widescreen": true, "service_video_id": "4KUO7iOnwC4", "length": 600, "mature": false}', true ) );
            $video->tags()->attach( $tagId( "Health" ) );
            $video->tags()->attach( $tagId( "Fitness" ) );
            $video->save();
            
            $video = App\Video::create( json_decode( '{"graphic": false, "service": "y", "title": "VEGAN WAITER - Sketch", "widescreen": true, "service_video_id": "NVfGjvZ8WiI", "length": 156, "mature": false}', true ) );
            $video->tags()->attach( $tagId( "Humor" ) );
            $video->tags()->attach( $tagId( "Ethics" ) );
            $video->tags()->attach( $tagId( "Information" ) );
            $video->tags()->attach( $tagId( "Sketches" ) );
            $video->save();
            
            $video = App\Video::create( json_decode( '{"graphic": true, "service": "y", "title": "Undercover Video of Bettencourt Dairies in Idaho", "widescreen": true, "service_video_id": "eauq54XScE4", "length": 132, "mature": false}', true ) );
            $video->tags()->attach( $tagId( "Ethics" ) );
            $video->tags()->attach( $tagId( "Information" ) );
            $video->tags()->attach( $tagId( "Undercover" ) );
            $video->save();
            
            $video = App\Video::create( json_decode( '{"graphic": false, "service": "y", "title": "You Can\'t Love Animals and Eat Them | Change My Mind (Part 2)", "widescreen": true, "service_video_id": "PrKAycD7LRo", "length": 2224, "mature": false}', true ) );
            $video->tags()->attach( $tagId( "Ethics" ) );
            $video->tags()->attach( $tagId( "Activism" ) );
            $video->tags()->attach( $tagId( "Speech" ) );
            $video->tags()->attach( $tagId( "Debate" ) );
            $video->save();
            
            $video = App\Video::create( json_decode( '{"graphic": false, "service": "y", "title": "ULTIMATE GUIDE TO BEING A FIT VEGAN", "widescreen": true, "service_video_id": "s_HsuKjxPkg", "length": 777, "mature": false}', true ) );
            $video->tags()->attach( $tagId( "Health" ) );
            $video->tags()->attach( $tagId( "Fitness" ) );
            $video->save();
            
            $video = App\Video::create( json_decode( '{"graphic": false, "service": "y", "title": "This Man Will Inspire You - James Aspey", "widescreen": true, "service_video_id": "a22XxXP3nU8", "length": 601, "mature": false}', true ) );
            $video->tags()->attach( $tagId( "Ethics" ) );
            $video->tags()->attach( $tagId( "Inspiring" ) );
            $video->tags()->attach( $tagId( "Information" ) );
            $video->tags()->attach( $tagId( "Speech" ) );
            $video->save();
            
            $video = App\Video::create( json_decode( '{"graphic": false, "service": "y", "title": "The Media Bias Against Veganism - The Disclosure Podcast (Episode 1)", "widescreen": true, "service_video_id": "yWdkC8ExuUk", "length": 5037, "mature": false}', true ) );
            $video->tags()->attach( $tagId( "Ethics" ) );
            $video->tags()->attach( $tagId( "Information" ) );
            $video->tags()->attach( $tagId( "Podcast" ) );
            $video->save();
            
            $video = App\Video::create( json_decode( '{"graphic": false, "service": "y", "title": "Vegan Takes on Venice Beach (Part 2)", "widescreen": true, "service_video_id": "95O-WMpe7LQ", "length": 976, "mature": false}', true ) );
            $video->tags()->attach( $tagId( "Debate" ) );
            $video->save();
            
            $video = App\Video::create( json_decode( '{"graphic": false, "service": "y", "title": "How To Become A Vegan Activist", "widescreen": true, "service_video_id": "oW682wH7078", "length": 630, "mature": false}', true ) );
            $video->tags()->attach( $tagId( "Ethics" ) );
            $video->tags()->attach( $tagId( "Inspiring" ) );
            $video->tags()->attach( $tagId( "Activism" ) );
            $video->save();
            
            $video = App\Video::create( json_decode( '{"graphic": true, "service": "y", "title": "Earthlings Documentary", "widescreen": true, "service_video_id": "ChiGijkR46k", "length": 5747, "mature": false}', true ) );
            $video->tags()->attach( $tagId( "Ethics" ) );
            $video->tags()->attach( $tagId( "Documentary" ) );
            $video->tags()->attach( $tagId( "Information" ) );
            $video->save();
            
            $video = App\Video::create( json_decode( '{"graphic": false, "service": "y", "title": "Speech on Animal Rights by Phillip Wollen", "widescreen": true, "service_video_id": "vBx7MGIZ1fU", "length": 1207, "mature": false}', true ) );
            $video->tags()->attach( $tagId( "Ethics" ) );
            $video->tags()->attach( $tagId( "Inspiring" ) );
            $video->tags()->attach( $tagId( "Speech" ) );
            $video->tags()->attach( $tagId( "Recipes" ) );
            $video->save();
            
            $video = App\Video::create( json_decode( '{"graphic": false, "service": "y", "title": "DEBATE: Vegan Activist Meets Irish Dairy Farmer (The Disclosure Podcast - Episode 5)", "widescreen": true, "service_video_id": "WFdgfSuzWwI", "length": 7420, "mature": false}', true ) );
            $video->tags()->attach( $tagId( "Environment" ) );
            $video->tags()->attach( $tagId( "Ethics" ) );
            $video->tags()->attach( $tagId( "Health" ) );
            $video->tags()->attach( $tagId( "Information" ) );
            $video->tags()->attach( $tagId( "Debate" ) );
            $video->tags()->attach( $tagId( "Podcast" ) );
            $video->save();
            
            $video = App\Video::create( json_decode( '{"graphic": false, "service": "y", "title": "How To Go Vegan The Right Way! Vegan Tips For Beginners", "widescreen": true, "service_video_id": "VvHABFmRvyE", "length": 1377, "mature": false}', true ) );
            $video->save();
            
            $video = App\Video::create( json_decode( '{"graphic": false, "service": "y", "title": "Can You Love Animals and Eat Them?", "widescreen": true, "service_video_id": "7mjVwVDDI8E", "length": 160, "mature": false}', true ) );
            $video->tags()->attach( $tagId( "Ethics" ) );
            $video->tags()->attach( $tagId( "Arguments" ) );
            $video->save();
            
            $video = App\Video::create( json_decode( '{"graphic": false, "service": "y", "title": "Will We Ever See a Vegan World?", "widescreen": true, "service_video_id": "tawFvfeHhQ0", "length": 226, "mature": false}', true ) );
            $video->tags()->attach( $tagId( "Inspiring" ) );
            $video->save();
            
            $video = App\Video::create( json_decode( '{"graphic": true, "service": "y", "title": "Vegan Visits UK Pig Farm", "widescreen": true, "service_video_id": "beZolR1nxj8", "length": 269, "mature": false}', true ) );
            $video->tags()->attach( $tagId( "Activism" ) );
            $video->save();
            
            $video = App\Video::create( json_decode( '{"graphic": false, "service": "y", "title": "The Vegan Prophecy - Joey Carbstrong", "widescreen": true, "service_video_id": "3Intje_Pb1Y", "length": 1305, "mature": false}', true ) );
            $video->tags()->attach( $tagId( "Ethics" ) );
            $video->tags()->attach( $tagId( "Inspiring" ) );
            $video->tags()->attach( $tagId( "Activism" ) );
            $video->tags()->attach( $tagId( "Speech" ) );
            $video->save();
            
            $video = App\Video::create( json_decode( '{"graphic": false, "service": "y", "title": "Veganism Is Unhealthy", "widescreen": true, "service_video_id": "XOI6FbEE5Jc", "length": 178, "mature": false}', true ) );
            $video->tags()->attach( $tagId( "Health" ) );
            $video->tags()->attach( $tagId( "Arguments" ) );
            $video->save();
            
            $video = App\Video::create( json_decode( '{"graphic": false, "service": "y", "title": "It\'s My Personal Choice To Eat Animals!", "widescreen": true, "service_video_id": "LseSfTA1BMw", "length": 180, "mature": false}', true ) );
            $video->tags()->attach( $tagId( "Ethics" ) );
            $video->tags()->attach( $tagId( "Arguments" ) );
            $video->save();
            
            $video = App\Video::create( json_decode( '{"graphic": false, "service": "y", "title": "Plants Feel Pain", "widescreen": true, "service_video_id": "EqUFqaeZA2g", "length": 165, "mature": false}', true ) );
            $video->tags()->attach( $tagId( "Ethics" ) );
            $video->tags()->attach( $tagId( "Arguments" ) );
            $video->save();
            
            $video = App\Video::create( json_decode( '{"graphic": false, "service": "y", "title": "I Love How Animals Taste!", "widescreen": true, "service_video_id": "w7sn6gyxMvE", "length": 188, "mature": false}', true ) );
            $video->tags()->attach( $tagId( "Ethics" ) );
            $video->tags()->attach( $tagId( "Arguments" ) );
            $video->save();
            
            $video = App\Video::create( json_decode( '{"graphic": true, "service": "y", "title": "The Truth About Backyard Eggs", "widescreen": true, "service_video_id": "GxO2-WREo50", "length": 195, "mature": false}', true ) );
            $video->tags()->attach( $tagId( "Ethics" ) );
            $video->tags()->attach( $tagId( "Information" ) );
            $video->save();
            
            $video = App\Video::create( json_decode( '{"graphic": true, "service": "y", "title": "Why Vegans Want You To Be Vegan", "widescreen": true, "service_video_id": "CTqFv_XMxHw", "length": 341, "mature": false}', true ) );
            $video->tags()->attach( $tagId( "Ethics" ) );
            $video->tags()->attach( $tagId( "Inspiring" ) );
            $video->save();
            
            $video = App\Video::create( json_decode( '{"graphic": false, "service": "y", "title": "God Says That I Can Eat Animals", "widescreen": true, "service_video_id": "2-R1yJeFtHE", "length": 298, "mature": false}', true ) );
            $video->tags()->attach( $tagId( "Ethics" ) );
            $video->tags()->attach( $tagId( "Arguments" ) );
            $video->save();
            
            $video = App\Video::create( json_decode( '{"graphic": false, "service": "y", "title": "You Can\'t Be 100% Vegan", "widescreen": true, "service_video_id": "1nDCx8AdZKI", "length": 163, "mature": false}', true ) );
            $video->tags()->attach( $tagId( "Arguments" ) );
            $video->save();
            
            $video = App\Video::create( json_decode( '{"graphic": false, "service": "y", "title": "If the World Went Vegan, What Would Happen to the Animals?", "widescreen": true, "service_video_id": "1M1fKxjlLV4", "length": 126, "mature": false}', true ) );
            $video->tags()->attach( $tagId( "Arguments" ) );
            $video->save();
            
            $video = App\Video::create( json_decode( '{"graphic": false, "service": "y", "title": "Being Vegetarian is Enough", "widescreen": true, "service_video_id": "uWna6-niYEg", "length": 280, "mature": false}', true ) );
            $video->tags()->attach( $tagId( "Ethics" ) );
            $video->tags()->attach( $tagId( "Arguments" ) );
            $video->save();
            
            $video = App\Video::create( json_decode( '{"graphic": false, "service": "y", "title": "Animals Eat Other Animals", "widescreen": true, "service_video_id": "lyQyI280YEo", "length": 161, "mature": false}', true ) );
            $video->tags()->attach( $tagId( "Ethics" ) );
            $video->tags()->attach( $tagId( "Arguments" ) );
            $video->save();
            
            $video = App\Video::create( json_decode( '{"graphic": false, "service": "y", "title": "Environmental Benefits of Veganism", "widescreen": true, "service_video_id": "2bvoJAfjWMM", "length": 457, "mature": false}', true ) );
            $video->tags()->attach( $tagId( "Environment" ) );
            $video->tags()->attach( $tagId( "Information" ) );
            $video->tags()->attach( $tagId( "Speech" ) );
            $video->save();
            
            $video = App\Video::create( json_decode( '{"graphic": false, "service": "y", "title": "Human Rights Issues are More Important Than Veganism", "widescreen": true, "service_video_id": "G66fBppXw4I", "length": 217, "mature": false}', true ) );
            $video->tags()->attach( $tagId( "Ethics" ) );
            $video->tags()->attach( $tagId( "Arguments" ) );
            $video->save();
            
            $video = App\Video::create( json_decode( '{"graphic": false, "service": "y", "title": "Are Backyard Eggs Ethical? + Staying Calm & My Non-Vegan Family (The Disclosure Podcast - Ep 4", "widescreen": true, "service_video_id": "UMLZevCwXC4", "length": 4041, "mature": false}', true ) );
            $video->tags()->attach( $tagId( "Ethics" ) );
            $video->tags()->attach( $tagId( "Information" ) );
            $video->tags()->attach( $tagId( "Podcast" ) );
            $video->save();
            
            $video = App\Video::create( json_decode( '{"graphic": false, "service": "y", "title": "One Person Can\'t Make a Difference", "widescreen": true, "service_video_id": "d6fG1my3SFg", "length": 246, "mature": false}', true ) );
            $video->tags()->attach( $tagId( "Arguments" ) );
            $video->save();
            
            $video = App\Video::create( json_decode( '{"graphic": false, "service": "y", "title": "Going Vegan is Expensive and Restrictive", "widescreen": true, "service_video_id": "Vs_nXVmyP1E", "length": 228, "mature": false}', true ) );
            $video->tags()->attach( $tagId( "Arguments" ) );
            $video->save();
            
            $video = App\Video::create( json_decode( '{"graphic": false, "service": "y", "title": "Jay Brave | Vegan Shut Up (Stormzy Parody)", "widescreen": true, "service_video_id": "DgdberK0q_Y", "length": 191, "mature": false}', true ) );
            $video->tags()->attach( $tagId( "Music" ) );
            $video->save();
            
            $video = App\Video::create( json_decode( '{"graphic": false, "service": "y", "title": "Hitler Was a Vegetarian/I Once Met a Mean Vegan", "widescreen": true, "service_video_id": "8rzdZqjCDdo", "length": 189, "mature": false}', true ) );
            $video->tags()->attach( $tagId( "Ethics" ) );
            $video->tags()->attach( $tagId( "Arguments" ) );
            $video->save();
            
            $video = App\Video::create( json_decode( '{"graphic": false, "service": "y", "title": "Humans Are at the Top of the Food Chain", "widescreen": true, "service_video_id": "-truOzeWBR8", "length": 181, "mature": false}', true ) );
            $video->tags()->attach( $tagId( "Ethics" ) );
            $video->tags()->attach( $tagId( "Arguments" ) );
            $video->save();
            
            $video = App\Video::create( json_decode( '{"graphic": false, "service": "y", "title": "We\'re Omnivores/We Have Canine Teeth", "widescreen": true, "service_video_id": "Hq23d8aI5LE", "length": 169, "mature": false}', true ) );
            $video->tags()->attach( $tagId( "Ethics" ) );
            $video->tags()->attach( $tagId( "Arguments" ) );
            $video->save();
            
            $video = App\Video::create( json_decode( '{"graphic": false, "service": "y", "title": "The Dark Confessions of an Ex-Animal Farmer (The Disclosure Podcast - Episode 3)", "widescreen": true, "service_video_id": "RE8LF3iP6AA", "length": 4675, "mature": false}', true ) );
            $video->tags()->attach( $tagId( "Ethics" ) );
            $video->tags()->attach( $tagId( "Information" ) );
            $video->tags()->attach( $tagId( "Undercover" ) );
            $video->tags()->attach( $tagId( "Podcast" ) );
            $video->save();
            
            $video = App\Video::create( json_decode( '{"graphic": false, "service": "y", "title": "How I Built Muscle on a Vegan Diet - Efficient Training Programming", "widescreen": true, "service_video_id": "fMFZN9YIycI", "length": 507, "mature": false}', true ) );
            $video->tags()->attach( $tagId( "Health" ) );
            $video->tags()->attach( $tagId( "Fitness" ) );
            $video->save();
            
            $video = App\Video::create( json_decode( '{"graphic": false, "service": "y", "title": "How to Build Muscle On A Vegan Diet", "widescreen": true, "service_video_id": "NHv5F2ALYXU", "length": 1915, "mature": false}', true ) );
            $video->tags()->attach( $tagId( "Health" ) );
            $video->tags()->attach( $tagId( "Fitness" ) );
            $video->save();
            
            $video = App\Video::create( json_decode( '{"graphic": false, "service": "y", "title": "Everything in Moderation", "widescreen": true, "service_video_id": "Z-S21l0Xa_s", "length": 191, "mature": false}', true ) );
            $video->tags()->attach( $tagId( "Arguments" ) );
            $video->save();
            
            $video = App\Video::create( json_decode( '{"graphic": false, "service": "y", "title": "Our Ancestors Ate Animals", "widescreen": true, "service_video_id": "YJtSoZPgaz0", "length": 167, "mature": false}', true ) );
            $video->tags()->attach( $tagId( "Arguments" ) );
            $video->save();
            
            $video = App\Video::create( json_decode( '{"graphic": false, "service": "y", "title": "What if a Vegan Was Stranded on a Desert Island?", "widescreen": true, "service_video_id": "eqAiCOzHAPY", "length": 103, "mature": false}', true ) );
            $video->tags()->attach( $tagId( "Ethics" ) );
            $video->tags()->attach( $tagId( "Arguments" ) );
            $video->save();
            
            $video = App\Video::create( json_decode( '{"graphic": false, "service": "y", "title": "Soya Farming is Destroying the Environment", "widescreen": true, "service_video_id": "SzOeOfNFpts", "length": 172, "mature": false}', true ) );
            $video->tags()->attach( $tagId( "Environment" ) );
            $video->tags()->attach( $tagId( "Arguments" ) );
            $video->save();
            
            $video = App\Video::create( json_decode( '{"graphic": false, "service": "y", "title": "My Friends and Family Will Judge me if I go Vegan (Advice on Going Vegan)", "widescreen": true, "service_video_id": "oSlm3-7uriM", "length": 296, "mature": false}', true ) );
            $video->tags()->attach( $tagId( "Arguments" ) );
            $video->save();
            
            $video = App\Video::create( json_decode( '{"graphic": false, "service": "y", "title": "Can\'t We Just Improve the Welfare of Animals?", "widescreen": true, "service_video_id": "02GNr5DnPCk", "length": 328, "mature": false}', true ) );
            $video->tags()->attach( $tagId( "Ethics" ) );
            $video->tags()->attach( $tagId( "Arguments" ) );
            $video->save();
            
            $video = App\Video::create( json_decode( '{"graphic": false, "service": "y", "title": "Morality is Subjective", "widescreen": true, "service_video_id": "xG4CHQdrSpc", "length": 145, "mature": false}', true ) );
            $video->tags()->attach( $tagId( "Ethics" ) );
            $video->tags()->attach( $tagId( "Arguments" ) );
            $video->save();
            
            $video = App\Video::create( json_decode( '{"graphic": true, "service": "y", "title": "Land of Hope and Glory Trailer", "widescreen": true, "service_video_id": "OqPflP_hXyY", "length": 73, "mature": false}', true ) );
            $video->tags()->attach( $tagId( "Documentary" ) );
            $video->save();
            
            $video = App\Video::create( json_decode( '{"graphic": false, "service": "y", "title": "Eating Animals is the Circle of Life", "widescreen": true, "service_video_id": "iL5M6Kc27SU", "length": 216, "mature": false}', true ) );
            $video->tags()->attach( $tagId( "Ethics" ) );
            $video->tags()->attach( $tagId( "Arguments" ) );
            $video->save();
            
            $video = App\Video::create( json_decode( '{"graphic": false, "service": "y", "title": "It\'s Cultural and Traditional to Eat Animals", "widescreen": true, "service_video_id": "0tItNLwMT_g", "length": 141, "mature": false}', true ) );
            $video->tags()->attach( $tagId( "Arguments" ) );
            $video->save();
            
            $video = App\Video::create( json_decode( '{"graphic": false, "service": "y", "title": "Do Animals Feel Pain?", "widescreen": true, "service_video_id": "nIP5Yrqdugc", "length": 203, "mature": false}', true ) );
            $video->tags()->attach( $tagId( "Ethics" ) );
            $video->tags()->attach( $tagId( "Arguments" ) );
            $video->save();
            
            $video = App\Video::create( json_decode( '{"graphic": false, "service": "y", "title": "What About Farmer\'s Jobs?", "widescreen": true, "service_video_id": "l3-OxcOlMJ0", "length": 218, "mature": false}', true ) );
            $video->tags()->attach( $tagId( "Arguments" ) );
            $video->save();
            
            $video = App\Video::create( json_decode( '{"graphic": false, "service": "y", "title": "An Introduction to Animal Rights", "widescreen": true, "service_video_id": "jGyCxnMdpUg", "length": 2995, "mature": false}', true ) );
            $video->tags()->attach( $tagId( "Ethics" ) );
            $video->tags()->attach( $tagId( "Speech" ) );
            $video->save();
            
            $video = App\Video::create( json_decode( '{"graphic": false, "service": "y", "title": "Animals Are Bred to be Killed", "widescreen": true, "service_video_id": "_L84EXgRVhY", "length": 118, "mature": false}', true ) );
            $video->tags()->attach( $tagId( "Ethics" ) );
            $video->tags()->attach( $tagId( "Arguments" ) );
            $video->save();
            
            $video = App\Video::create( json_decode( '{"graphic": false, "service": "y", "title": "We Are More Intelligent Than Animals", "widescreen": true, "service_video_id": "-6qhtS5moFM", "length": 134, "mature": false}', true ) );
            $video->tags()->attach( $tagId( "Ethics" ) );
            $video->tags()->attach( $tagId( "Arguments" ) );
            $video->save();
            
            $video = App\Video::create( json_decode( '{"graphic": false, "service": "y", "title": "The Secret Weapon: Food Marketing", "widescreen": true, "service_video_id": "Q5pB-OUEgks", "length": 419, "mature": false}', true ) );
            $video->tags()->attach( $tagId( "Ethics" ) );
            $video->tags()->attach( $tagId( "Information" ) );
            $video->tags()->attach( $tagId( "Speech" ) );
            $video->save();
            
            $video = App\Video::create( json_decode( '{"graphic": false, "service": "y", "title": "Why Farmed Animals Should be Grateful", "widescreen": true, "service_video_id": "pueLyA1lIcA", "length": 237, "mature": false}', true ) );
            $video->tags()->attach( $tagId( "Ethics" ) );
            $video->tags()->attach( $tagId( "Arguments" ) );
            $video->save();
            
            $video = App\Video::create( json_decode( '{"graphic": false, "service": "y", "title": "Inside the Mind of an Undercover Investigator (The Disclosure Podcast - Episode 6)", "widescreen": true, "service_video_id": "5WtfU8Jw6io", "length": 4889, "mature": false}', true ) );
            $video->tags()->attach( $tagId( "Ethics" ) );
            $video->tags()->attach( $tagId( "Information" ) );
            $video->tags()->attach( $tagId( "Podcast" ) );
            $video->save();
            
            $video = App\Video::create( json_decode( '{"graphic": false, "service": "y", "title": "The Science of Social Change", "widescreen": true, "service_video_id": "NWHqJpcgjk0", "length": 1974, "mature": false}', true ) );
            $video->tags()->attach( $tagId( "Information" ) );
            $video->save();
            
            $video = App\Video::create( json_decode( '{"graphic": true, "service": "y", "title": "40 NON-VEGANS TRICKED to WATCH DOMINION", "widescreen": true, "service_video_id": "Ey6eDNJJv_I", "length": 2282, "mature": false}', true ) );
            $video->tags()->attach( $tagId( "Inspiring" ) );
            $video->tags()->attach( $tagId( "Information" ) );
            $video->tags()->attach( $tagId( "Activism" ) );
            $video->save();
            
            $video = App\Video::create( json_decode( '{"graphic": true, "service": "y", "title": "(EPIC) MEAT EATER VS VEGAN", "widescreen": true, "service_video_id": "ZE29zYwtt8s", "length": 332, "mature": false}', true ) );
            $video->tags()->attach( $tagId( "Ethics" ) );
            $video->tags()->attach( $tagId( "Inspiring" ) );
            $video->tags()->attach( $tagId( "Music" ) );
            $video->save();
            
            $video = App\Video::create( json_decode( '{"graphic": false, "service": "y", "title": "Why Direct Action? A Talk by Wayne Hsiung", "widescreen": true, "service_video_id": "DwjRdfibk7M", "length": 895, "mature": false}', true ) );
            $video->tags()->attach( $tagId( "Inspiring" ) );
            $video->tags()->attach( $tagId( "Information" ) );
            $video->tags()->attach( $tagId( "Activism" ) );
            $video->save();
            
            $video = App\Video::create( json_decode( '{"graphic": false, "service": "y", "title": "Whose Side Are You On?", "widescreen": true, "service_video_id": "kIFPKgithu4", "length": 93, "mature": false}', true ) );
            $video->tags()->attach( $tagId( "Ethics" ) );
            $video->tags()->attach( $tagId( "Documentary" ) );
            $video->save();
            
            $video = App\Video::create( json_decode( '{"graphic": true, "service": "y", "title": "How Ableism Hurts Animals", "widescreen": true, "service_video_id": "SxBqoqH6RWE", "length": 1474, "mature": false}', true ) );
            $video->tags()->attach( $tagId( "Ethics" ) );
            $video->tags()->attach( $tagId( "Information" ) );
            $video->tags()->attach( $tagId( "Activism" ) );
            $video->save();
            
            $video = App\Video::create( json_decode( '{"graphic": false, "service": "y", "title": "The Save Movement - Vegan Activism", "widescreen": true, "service_video_id": "TgczQju9sbY", "length": 317, "mature": false}', true ) );
            $video->tags()->attach( $tagId( "Ethics" ) );
            $video->tags()->attach( $tagId( "Information" ) );
            $video->tags()->attach( $tagId( "Activism" ) );
            $video->save();
            
            $video = App\Video::create( json_decode( '{"graphic": false, "service": "y", "title": "Live Your Most Compassionate Life", "widescreen": true, "service_video_id": "aOTe-r59oqE", "length": 247, "mature": false}', true ) );
            $video->tags()->attach( $tagId( "Ethics" ) );
            $video->tags()->attach( $tagId( "Documentary" ) );
            $video->save();
            
            $video = App\Video::create( json_decode( '{"graphic": true, "service": "y", "title": "Beyond the Lies", "widescreen": true, "service_video_id": "OW3y_TztrWw", "length": 287, "mature": false}', true ) );
            $video->tags()->attach( $tagId( "Ethics" ) );
            $video->tags()->attach( $tagId( "Documentary" ) );
            $video->tags()->attach( $tagId( "Undercover" ) );
            $video->save();
            
            $video = App\Video::create( json_decode( '{"graphic": false, "service": "y", "title": "Vegan Communication: The Problem and the Promise", "widescreen": true, "service_video_id": "XfNoiOlef2U", "length": 2699, "mature": false}', true ) );
            $video->tags()->attach( $tagId( "Information" ) );
            $video->tags()->attach( $tagId( "Activism" ) );
            $video->tags()->attach( $tagId( "Speech" ) );
            $video->save();
            
            $video = App\Video::create( json_decode( '{"graphic": false, "service": "y", "title": "Vegan Rap 2 - Kyle O\'Sullivan Animal Rights March", "widescreen": true, "service_video_id": "8JhL6dB9Dbo", "length": 180, "mature": false}', true ) );
            $video->tags()->attach( $tagId( "Ethics" ) );
            $video->tags()->attach( $tagId( "Inspiring" ) );
            $video->tags()->attach( $tagId( "Activism" ) );
            $video->tags()->attach( $tagId( "Music" ) );
            $video->save();
            
            $video = App\Video::create( json_decode( '{"graphic": false, "service": "y", "title": "Patrik Baboumian - World Strongest Man, he\'s VEGAN!", "widescreen": false, "service_video_id": "JeA3EK98TBg", "length": 73, "mature": false}', true ) );
            $video->tags()->attach( $tagId( "Inspiring" ) );
            $video->tags()->attach( $tagId( "Fitness" ) );
            $video->tags()->attach( $tagId( "News" ) );
            $video->save();
            
            $video = App\Video::create( json_decode( '{"graphic": true, "service": "y", "title": "I Can\'t Bring Myself to Watch it", "widescreen": true, "service_video_id": "cWGmvR5uH3k", "length": 126, "mature": false}', true ) );
            $video->tags()->attach( $tagId( "Inspiring" ) );
            $video->tags()->attach( $tagId( "Activism" ) );
            $video->save();
            
        }

}